### ISSUE TITLE
我看了下 hash table 中 ttl 字段相关代码，有点不清楚的地方

### ISSUE THREAD

**Issue by Cofyc** [DNSPod/dnspod-sr#30]
按我的理解，ttl 字段：

- 如果是 MAX_TTL + 1，就永远不过期，返回时 TTL 字段为 MAX_TTL
- 非 MAX_TTL 的，过期时间就为 ttl，返回时 TTL 字段为 ttl - global_now (当前时间）

每隔一秒请求，会减一，600, 599, 598 这样，直到下次刷新。

但我测试，你们服务器始终返回 dnspod 面板里配置的值 600 不变：

```
$ dig www.xd.com @ns1.dnsv5.com A
// removed
xd.com.			600	IN	NS	ns2.dnsv5.com.
// removed
```

难道你们线上服务器每秒都在刷新？

**Comment by jfb8856606** [comment]
这是递归DNS和权威DNS的不同，递归DNS是缓存服务器，他的TTL是随时间减小的，过期后需要重新向授权请求；权威DNS是起始授权机构，一搬是返回纪录给递归DNS的，TTL返回的总是设置的值，不存在缓存过期的问题。

发自我的 iPhone

**Comment by Cofyc** [comment]
明白了，谢！

—
Yecheng Fu
