### ISSUE TITLE
是否支持 泛解析

### ISSUE THREAD

**Issue by liuwei881** [DNSPod/dnspod-sr#45]
是否支持 *.test.com 这种解析?

**Comment by jfb8856606** [comment]
暂不支持，后续可能会更新支持。
*一般用于设置授权DNS的解析主机记录，作为值或者向递归请求有支持的有不支持的。
但可以简单的修改进行支持，在dns.c文件中，将DnsNameTable的第0X2A项(390行倒数第六个元素）由"0"改为"0X2A:即可支持。

**Comment by liuwei881** [comment]
//check dns name and to lower table
unsigned char DnsNameTable[256] = {
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0X2A,0,0,0X2D,0,0,
改完后 重新make，不生效?

**Comment by jfb8856606** [comment]
测试是可以的，或者下载最新的代码，已经支持了泛解析*，同时需要域名的授权dns支持直接请求‘*’，并设置了泛解析。
