### ISSUE TITLE
配置文件路径修改

### ISSUE THREAD

**Issue by itcto** [DNSPod/dnspod-sr#48]
默认运行方式是:
```
make
cd dnspod-sr/src
./dnspod-sr
```

在 src/config.h 中配置文件使用相对路径 ../*.z ，如果想使用 supervisor 来管理 dnspod-sr 进程是做不到的，因为路径问题不支持  cd dnspod-sr/src &&  ./dnspod-sr 的方式，所以可以修改一下 config.h 为：

```
#define SR_CONFIG_FILE "/sr.conf"
#define SR_ROOT_FILE "/root.z"
#define SR_RECORDS_FILE "/records.z"
```

这样就可以使用全路径来运行 dnspod-sr 了：/full/path/to/dnspod-sr 。

**Comment by itcto** [comment]
摸索一阵子，在不修改任何程序代码的情况下，这样可以解决问题：

#### step1：把 dnspod-sr/src/dnspod-sr 加入 $PATH

> vim /etc/profile.d/myenv.sh

```
# dnspod-sr
export DNSPOD_HOME=/usr/local/dnspod-sr
export PATH=$DNSPOD_HOME/src:$PATH
```

> source /etc/profile

#### step2: 在 supervisor 配置中设置 dnspod-sr/src/dnspod-sr 的全路径

```
directory=/usr/local/dnspod-sr/src
command=dnspod-sr
```

**Comment by jfb8856606** [comment]
可以修改config.h，将配置文件的路径实际所在的全路径。
